apiVersion: 1
kind: ConfigMap
metadata:
  name: configmap-prometheus-global-alerting-rules
  namespace: kube-monitor
data:
  rules.yaml: |-
    groups:
    - name:
      rules:
      - alert: Cluster CPU usage high
        expr: sum(kube_pod_container_resource_requests_cpu_cores{node=~"$node"}) / sum(kube_node_status_allocatable_cpu_cores{node=~"$node"}) > .8
        for: 10m
        labels:
          severity: high
        annotations:
          summary: Cluster CPU usage is above 80%
      - alert: Cluster CPU usage very high
        expr: sum(kube_pod_container_resource_requests_cpu_cores{node=~"$node"}) / sum(kube_node_status_allocatable_cpu_cores{node=~"$node"}) > .9
        for: 6m
        labels:
          severity: severe
        annotations:
          summary: Cluster CPU usage is above 90%
      - alert: Cluster memory usage high
        expr: sum(kube_pod_container_resource_requests_memory_bytes{node=~"$node"}) / sum(kube_node_status_allocatable_memory_bytes{node=~"$node"}) > .8
        for: 10m
        labels:
          severity: high
        annotations:
          summary: Cluster memory usage is above 80%
      - alert: Cluster memory usage very high
        expr: sum(kube_pod_container_resource_requests_memory_bytes{node=~"$node"}) / sum(kube_node_status_allocatable_memory_bytes{node=~"$node"}) > .9
        for: 6m
        labels:
          severity: severe
        annotations:
          summary: Cluster memory usage is above 90%
      - alert: Cluster disk usage high
        expr: (sum (node_filesystem_size{nodename=~"$node"}) - sum (node_filesystem_free{nodename=~"$node"})) / sum (node_filesystem_size{nodename=~"$node"}) > .8
        for: 10m
        labels:
          severity: high
        annotations:
          summary: Cluster disk usage is above 80%
      - alert: Cluster disk usage high
        expr: expr: (sum (node_filesystem_size{nodename=~"$node"}) - sum (node_filesystem_free{nodename=~"$node"})) / sum (node_filesystem_size{nodename=~"$node"}) > .9
        for: 6m
        labels:
          severity: severe
        annotations:
          summary: Cluster disk usage is above 90%
      - alert: Node out of disk
        expr: sum(kube_node_status_condition{condition="OutOfDisk", node=~"$node", status="true"}) > 0
        for: 6m
        labels:
          severity: severe
        annotations:
          summary: Node out of disk
      - alert: Node unavailable
        expr: sum(kube_node_spec_unschedulable{node=~"$node"}) > 0
        for: 6m
        labels:
          severity: severe
        annotations:
          summary: Node unavailable
