---
apiVersion: v1
kind: Service
metadata:
  name: kube-monitor-prometheus-internal-lb
  namespace: kube-monitor
  annotations:
    #service.beta.kubernetes.io/aws-load-balancer-internal: '0.0.0.0/0'
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-central-1:645145707377:certificate/6e4f6c44-db6d-4feb-8621-ec42f3a29b69
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "App=eve-search,Finance=COGS"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    external-dns.alpha.kubernetes.io/hostname: prometheus-phoebe.ccp-cloud.net.
spec:
  ports:
    - name: https
      port: 443
      targetPort: 9090
  selector:
    app: prometheus
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: kube-monitor-prometheus-alertmanager-internal-lb
  namespace: kube-monitor
  annotations:
    #service.beta.kubernetes.io/aws-load-balancer-internal: '0.0.0.0/0'
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-central-1:645145707377:certificate/6e4f6c44-db6d-4feb-8621-ec42f3a29b69
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "App=eve-search,Finance=COGS"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    external-dns.alpha.kubernetes.io/hostname: alertmanager.prometheus-phoebe.ccp-cloud.net.
spec:
  ports:
    - name: https
      port: 443
      targetPort: 9093
  selector:
    app: prometheus
  type: LoadBalancer
