---
apiVersion: v1
kind: Service
metadata:
  name: kube-prometheus-exporter-node
  namespace: kube-monitor
spec:
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
    targetPort: metrics
  selector:
    app: kube-prometheus-exporter-node
    component: node-exporter
    release: kube-prometheus
  sessionAffinity: None
  type:
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kube-prometheus-exporter-kube-state
  namespace: kube-monitor
spec:
  ports:
  - name: kube-state-metrics
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: kube-prometheus-exporter-kube-state
    component: kube-state
    release: kube-prometheus
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kube-prometheus
  namespace: kube-monitor
spec:
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
    prometheus: kube-prometheus
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kube-prometheus-alertmanager
  namespace: kube-monitor
spec:
  ports:
  - name: http
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    alertmanager: kube-prometheus
    app: alertmanager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kube-prometheus-exporter-node
  namespace: kube-monitor
spec:
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
    targetPort: metrics
  selector:
    app: kube-prometheus-exporter-node
    component: node-exporter
    release: kube-prometheus
  sessionAffinity: None
  type:
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-operated
  namespace: kube-monitor
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    kind: Prometheus
    name: kube-prometheus
spec:
  clusterIP: None
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    app: prometheus
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
kind: List
metadata:
resourceVersion: ""
selfLink: ""
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-operated
  namespace: kube-monitor
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    kind: Alertmanager
    name: kube-prometheus
spec:
  ports:
  - name: web
    port: 9093
    protocol: TCP
    targetPort: 9093
  - name: mesh
    port: 6783
    protocol: TCP
    targetPort: 6783
  selector:
    app: alertmanager
  sessionAffinity: None
  type:
status:
  loadBalancer: {}
