apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
  namespace: kube-monitor
  labels:
    app: prometheus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      volumes:
      - name: configmap-prometheus-global
        configMap:
          name: configmap-prometheus-global
      - name: configmap-prometheus-global-alerting-rules
        configMap:
          name: configmap-prometheus-global-alerting-rules
      - name: prometheus-data-global
        persistentVolumeClaim:
          claimName: prometheus
      - name: prometheus-global-alertmanager
        secret:
          secretName: prometheus-global-alertmanager
      # `prometheus` docker image uses `nobody:nogroup` as uid and gid
      securityContext:
        fsGroup: 65534
      containers:
      # Prometheus Server
      - name: prometheus
        image: prom/prometheus:v2.1.0
        args:
          - "--config.file=/tmp/config/prometheus.yaml"
          - "--storage.tsdb.retention=15d"
          - "--storage.tsdb.path=/data"
          - "--web.external-url=https://prometheus-global.ccp-cloud.net"
        ports:
        - name: http
          containerPort: 9090
        volumeMounts:
        - name: configmap-prometheus-global
          mountPath: /tmp/config
          readOnly: true
        - name: configmap-prometheus-global-alerting-rules
          mountPath: /tmp/rules
          readOnly: true
        - name: prometheus-data-global
          mountPath: /data
        resources:
          limits:
            cpu: "1"
            memory: 1G
      # Alert Manager
      - name: alertmanager
        image: prom/alertmanager:v0.13.0
        args:
          - "--config.file=/tmp/alertmanager.yaml"
          - "--web.external-url=https://alertmanager.prometheus-global.ccp-cloud.net"
        ports:
        - name: http
          containerPort: 9093
        volumeMounts:
        - name: prometheus-global-alertmanager
          mountPath: /tmp
          readOnly: true
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
