apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: exporter-node
    component: node-exporter
    heritage: Tiller
    release: kube-prometheus
  name: kube-prometheus-exporter-node
  namespace: kube-monitor
spec:
  selector:
    matchLabels:
      app: kube-prometheus-exporter-node
      component: node-exporter
      release: kube-prometheus
  template:
    metadata:
      labels:
        app: kube-prometheus-exporter-node
        component: node-exporter
        release: kube-prometheus
    spec:
      containers:
      - args:
        - --web.listen-address=0.0.0.0:9100
        - --path.procfs=/host/proc
        - --path.sysfs=/host/sys
        image: quay.io/prometheus/node-exporter:v0.15.2
        imagePullPolicy: IfNotPresent
        name: node-exporter
        ports:
        - containerPort: 9100
          hostPort: 9100
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 30Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host/proc
          name: proc
          readOnly: true
        - mountPath: /host/sys
          name: sys
          readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      hostPID: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        operator: Exists
      volumes:
      - hostPath:
          path: /proc
          type: ""
        name: proc
      - hostPath:
          path: /sys
          type: ""
        name: sys
  templateGeneration: 1
  updateStrategy:
    type: OnDelete
